server:
  servlet:
    contextPath: /api
  port: 8080

spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
   username: postgres
   password: noah2001
   #url: jdbc:postgresql://10.20.0.46:5432/KNPS?currentSchema=developx
   #username: dbuser
   #password: dbuser 
   driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      springframework: ERROR
log4j:
  logger:
    jp:
      co:
        a7:
          trip:
            application:
              model: 
                mapper: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true

                