server:
  servlet:
    contextPath: /api
  port: 8080

spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
   username: postgres
   password: noah2001
   driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      springframework: DEBUG
log4j:
  logger:
    jp:
      co:
        a7:
          trip:
            application:
              model: 
                mapper: DEBUG